"""empty message

Revision ID: 06b6a39d0362
Revises: 1a78796eafef
Create Date: 2019-04-16 19:02:28.002291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b6a39d0362'
down_revision = '1a78796eafef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'nickname')
    # op.drop_column('user', 'tall')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('nickname')
        batch_op.drop_column('tall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tall', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('nickname', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
