"""empty message

Revision ID: 28d55a33be51
Revises: 3ca36022b118
Create Date: 2019-04-19 09:44:04.865113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d55a33be51'
down_revision = '3ca36022b118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'created_time')
    # ### end Alembic commands ###
